sudo: required
services:
  - docker

before_install:
  - docker build -t onxssis/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true onxssis/react-test npm test

after_success:
  - docker build -t onxssis/complex-client ./client
  - docker build -t onxssis/complex-server ./server
  - docker build -t onxssis/complex-nginx ./nginx
  - docker build -t onxssis/complex-worker ./worker
  # log in to docker hub and push built images
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push onxssis/complex-client
  - docker push onxssis/complex-server
  - docker push onxssis/complex-nginx
  - docker push onxssis/complex-worker
